---
title: "Lecture_7_Tidy_Data"
output: html_document
---
```{r}
library(tidyverse)
library(readxl)
library(haven)
```


##pivot longer
```{r}
pulse_df <-  
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
```
 Let us try to pivot 

```{r}
pulse_tidy <- 
  pulse_df %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to ="visit",
    names_prefix = "bdi_score_",
    values_to ="bdi"
  ) %>%
  mutate(
    visit = replace(visit, visit=="bl", "00m"),
    visit = factor(visit)) %>%
  arrange(id, visit)

pulse_tidy
```

##pivot wider

make a resulyt data table 

```{r}
analysis_df <- 
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    group_mean = c(4, 8, 3, 6),
    time =c("a", "b", "a", "b")
  )

analysis_df %>%
  pivot_wider(
    names_from ="time",
    values_from ="group_mean"
  ) %>%
  knitr::kable()
```

##bind_rows

Import LOTR movie words
```{r}
fellowship_df <- 
   read_excel("data/LotR_Words.xlsx", range ="F3:H6") %>%
  mutate(movie="fellowship_rings")

two_towers_df <- 
   read_excel("data/LotR_Words.xlsx", range ="B3:D6") %>%
  mutate(movie="two_towers")

return_king <- 
  read_excel("data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")

lotr_tidy <- 
  bind_rows(fellowship_df, two_towers_df, return_king) %>%
  janitor::clean_names() %>%
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "words") %>%
  mutate(race = str_to_lower(race)) %>% 
  select(movie, everything()) 

lotr_tidy
return_king
```
##Joins

Look at FAS data
Import and cleaning data 
```{r}
litters_df <- 
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), 3) %>%
  relocate(litter_number) %>%
  mutate(dose = str_to_lower(dose))
  
  
pups_df <- 
  read_csv("./data/FAS_pups.csv") %>%
  janitor::clean_names() %>%
  mutate(
    sex = recode(sex, `1` = "male", `2` = "female"),
    sex = factor(sex)) 
```


Now join two data set
```{r}
fas_df <- 
  left_join(pups_df, litters_df, by = "litter_number") %>% 
  relocate(litter_number, dose, day_of_tx)
```









##Questions
1. How to change the orgnized version back to the sumamry version?